version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:18.4.0 
    steps:
      - checkout
      - run:
          name: install dependecies
          command: npm install
      - run: npm run lint

  test:
      docker:
        - image: cimg/node:18.4.0 
      steps:
        - checkout
        - run:
            name: install dependecies
            command: npm install
        - run: npm run test


workflows:
  CI-workflow:
    jobs:
      - lint
      - test: 
          requires: 
          - lint
