version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:18.4.0 
    steps:
      - checkout
      - run:
          name: install dependecies
          command: yarn
      - run: npm run lint
      - run: ls
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  test:
      docker:
        - image: cimg/node:18.4.0 
      steps:
        - checkout
        - restore_cache:
            keys:
              - v1-deps-{{ checksum "yarn.lock" }}
        - run: ls
        - run: yarn
        - run: npm run test

  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Create Cloudformation Stack
          command: |
              aws cloudformation deploy \
                --template-file cloudFormation.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

workflows:
  CI-workflow:
    jobs:
      - lint
      - test: 
          requires: 
          - lint
      - create_infrastructure